version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=CalendarPlusPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql/data

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "CalendarPlusPassword123" -Q "create database Keycloak"; do sleep 5; done'

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mssql
      - DB_USER=sa
      - DB_PASSWORD=CalendarPlusPassword123
      - DB_ADDR=mssql
      - DB_DATABASE=Keycloak
    ports:
      - 8080:8080
    depends_on:
      - mssql
      - mssqlscripts
      
volumes:
  mssql:
  redis:
